[package]
org = "KavithLokuhewage"
name = "gqlAPI"
version = "1.0.0"
export = ["gqlAPI"]
distribution = "2201.3.1"
keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
icon = "docs/icon.png"

[build-options]
observabilityIncluded = true
